### PR TITLE
Feature/bi 1358

### PR DESCRIPTION
**Pull request by cvacalares**
TAF - refactor OntologyTermCreateMethodScaleClass.feature
Replace obsolete tests.

### CODE REVIEW

**Review by HMS17 — CHANGES_REQUESTED** [review]
Current issues from testing against bug/BI-1356

- Scenarios with unimplemented steps failing (BI-1351, BI-1352, BI-1353)
- Inability to clear value fields for ordinal scale, resulting in failure for BI-1344
- Step failure for BI-1350 on "Then user can not see "TEXT" in Nominal second field on ontology list page"
```
Error while running "elements" command: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null
TypeError: Error while running "elements" command: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null
```
-Step failure for BI-1348 on "Then user can not see Nominal second field text box on ontology list page"
  ` Error: Element "secondCategoryField" was not found in "traitsPage".`

**Comment by HMS17** [comment]
> Current issues from testing against bug/[BI-1356](https://breedinginsight.atlassian.net/browse/BI-1356)
> 
> * Scenarios with unimplemented steps failing ([BI-1351](https://breedinginsight.atlassian.net/browse/BI-1351), [BI-1352](https://breedinginsight.atlassian.net/browse/BI-1352), [BI-1353](https://breedinginsight.atlassian.net/browse/BI-1353))
> * Inability to clear value fields for ordinal scale, resulting in failure for [BI-1344](https://breedinginsight.atlassian.net/browse/BI-1344)
> * Step failure for [BI-1350](https://breedinginsight.atlassian.net/browse/BI-1350) on "Then user can not see "TEXT" in Nominal second field on ontology list page"
> 
> ```
> Error while running "elements" command: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null
> TypeError: Error while running "elements" command: Cannot read property 'element-6066-11e4-a52e-4f735466cecf' of null
> ```
> 
> -Step failure for [BI-1348](https://breedinginsight.atlassian.net/browse/BI-1348) on "Then user can not see Nominal second field text box on ontology list page" ` Error: Element "secondCategoryField" was not found in "traitsPage".`

Ran the full TAF suite against release/0.5 (as that is what has the ordinal nominal fixes) and went through the failures to see which are bugs on the BI end and which are likely TAF. The latter are listed below.

Problem seems to be incorrect selector
BI-948
BI-926
BI-929
BI-930
BI-1329

BI-1352 - X for deleting would be in third field, the first two rows for ordinal cannot be deleted, scenario should be updated accordingly
BI-1353 - Why is it checking for “1” rather than “TEXT” since the latter is in the row that is removed
BI-1327 - Screenshot displays an error message on save of “Error creating trait. Scale categories contain errors” but unfortunately isn’t scrolled up to see the contents of the form. Looking at the steps I suspect it might have to do with selecting ordinal and then having steps about setting nominal fields? Regardless of whether that is the cause, that should likely be modified as well to ensure clarity of the scenario.

**Comment by cvacalares** [comment]
BI-948 - Add step to click the "Show All" button to display all the entries before searching.
BI-1353 - I have updated the test steps in the story.

**Comment by cvacalares** [comment]
Full Run Test Result:
https://github.com/Breeding-Insight/taf/actions/runs/2020754168

4 Failures:
BI-948 - Trait column value now combination of trait entity and trait attribute. (Expected change or bug?)
BI-1352 - Category fields doesn't have the "x" for min required fields. (Expected change or bug?)
BI-1353 - Category fields initially doesn't have values in them, now it gets populated by default. (Expected change or bug?)
BI-1327 - I will remove extra steps to add the additional category (it was in place earlier due to a work still in progress)

Let me know about the issues I've raised if they are expected change or I need to log a bug.

**Comment by HMS17** [comment]
> Full Run Test Result: https://github.com/Breeding-Insight/taf/actions/runs/2020754168
> 
> 4 Failures: [BI-948](https://breedinginsight.atlassian.net/browse/BI-948) - Trait column value now combination of trait entity and trait attribute. (Expected change or bug?) [BI-1352](https://breedinginsight.atlassian.net/browse/BI-1352) - Category fields doesn't have the "x" for min required fields. (Expected change or bug?) [BI-1353](https://breedinginsight.atlassian.net/browse/BI-1353) - Category fields initially doesn't have values in them, now it gets populated by default. (Expected change or bug?) [BI-1327](https://breedinginsight.atlassian.net/browse/BI-1327) - I will remove extra steps to add the additional category (it was in place earlier due to a work still in progress)
> 
> Let me know about the issues I've raised if they are expected change or I need to log a bug.

Thanks for the update!

BI-948 - Expected change is trait column is entity + attribute
BI-1352 - Expected change to prevent user from removing a minimum required field
BI-1353 (and presumably BI-1344) - Expected change, ordinal category values are now initially populated by default. 

Let me know when the scenarios are updated to account for the new expected changes!

**Comment by cvacalares** [comment]
Can we approve the pull request as the failures are not due the changes here?
I will create separate branches for the bug fixes as well.
@timparsons @HMS17

**Review by HMS17 — APPROVED** [review]

**Review by timparsons — APPROVED** [review]

**Pull request merged**
